version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'smallkirby'
    labels:
      - 'dependencies'
  - package-ecosystem: 'npm'
    directory: '/functions'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'smallkirby'
    labels:
      - 'dependencies'
