version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    groups:
      react-next:
        dependency-type: production
        patterns:
          - 'react'
          - 'next'
      dev-dependencies:
        dependency-type: production
        patterns:
          - '*'
      prod-dependencies:
        dependency-type: production
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/functions'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    groups:
      firebase:
        dependency-type: production
        patterns:
          - 'firebase-admin'
          - 'firebase-functions'
      dev-dependencies:
        dependency-type: production
        patterns:
          - '*'
      prod-dependencies:
        dependency-type: production
        patterns:
          - '*'
