name: Deploy Functions & Firestore

on:
  push:
    branches:
      - master
    paths:
      - functions/**
      - firebase/**
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build functions
        run: cd functions && npm ci --no-audit && npm run build

      - name: Deploy Functions and Firestore
        uses: w9jds/firebase-action@7b6cebfa62d71e24d73832ee4b73dc1b0709f32d
        with:
          # `--only functions,firestore` does not work, why...?
          args: deploy --only firestore,functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVREC_4D401 }}
