name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci --no-audit && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVREC_4D401 }}'
          channelId: live
          projectId: favrec-4d401

      - name: Build functions
        run: cd functions && npm ci --no-audit && npm run build

      - name: Deploy Functions and Firestore
        uses: w9jds/firebase-action@master
        with:
          # `--only functions,firestore` does not work, why...?
          args: deploy --only firestore,functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVREC_4D401 }}
