name: Deploy Functions & Firestore

on:
  push:
    branches:
      - master
    paths:
      - functions/**
      - firebase/**
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVREC_4D401 }}

      - name: Install Dependencies
        run:
          npm ci --no-audit

      - name: Build functions
        run: cd functions && npm ci --no-audit && npm run build

      - name: Deploy Functions and Firestore
        run: npx firebase deploy --only functions,firestore
