name: E2E tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      - name: Build functions
        run: cd functions && npm ci --no-audit && npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload test results 📦
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
